### ISSUE TITLE
Crashes with python 3.9+ from xlrd; switch to OpenPyXL

### ISSUE THREAD

**Issue by ajeddeloh** [mjhoptics/opticalglass#2]
Python 3.9 removed the deprecated `getiterator()` function in favor of `iter()`. xlrd uses `getiterator()` and is abandonware at this point. The author of xlrd has [recommended switching to OpenPyXL](https://github.com/python-excel/xlrd#xlrd).

Workaround:

Edit the files in site-packages switching all `getiterator()` calls to `iter()`

**Comment by danieldmulkey** [comment]
Also, it looks like `from rayoptics.environment import *` fails when opticalglass/glass.py calls xlrd.open_workbook. It doesn't support the .xlsx files in the glass data folder.

This was on Python 3.8.3.

**Comment by danieldmulkey** [comment]
Thanks!
