### ISSUE TITLE
Use of python base classes for type checking leads to error with numpy

### ISSUE THREAD

**Issue by mmarras** [mjhoptics/opticalglass#3]
In `spectral_lines.py` the simple use of python numeric type checking leads to errors when using numpy numbers. `numpy` subclasses should be used instead. For a discussion see also [here](https://stackoverflow.com/questions/37726830/how-to-determine-if-a-number-is-any-type-of-int-core-or-numpy-signed-or-not).

Minimal example:
```
bk7= create_glass('N-BK7', 'Schott')
wvls = np.arange(450,1000,10)
nstore = []
for wvl in wvls:
    print(isinstance(wvl,np.integer))
    nstore.append(bk7.rindex(wvl))
```
fails with 

> 95         return float(wvl)
> 96     else:
> ---> 97         return spectra_uc[wvl.upper()]
> 
> AttributeError: 'numpy.int32' object has no attribute 'upper'
> 
Therefore `spectral_lines.py`'s 
```
    if isinstance(wvl, float):
        return wvl
    elif isinstance(wvl, int):
        return float(wvl)
    else:
        return spectra_uc[wvl.upper()]
```
should be 
```
import numpy as np
```
```
    if isinstance(wvl, np.float):
        return wvl
    elif isinstance(wvl, (int, np.integer)):
        return float(wvl)
    else:
        return spectra_uc[wvl.upper()]
```

**Comment by mjhoptics** [comment]
Created a new version, 0.7.2, with this fix and a few others including one that allows calc_rindex to take numpy arrays of wavelengths and return an array of refractive indices. So your example can be written:

bk7= create_glass('N-BK7', 'Schott')
wvls = np.arange(450,1000,10)
nstore = bk7.calc_rindex(wvls)

Thanks for suggesting the improvement.
