### ISSUE TITLE
make glass name case incensitive?

### ISSUE THREAD

**Issue by diplodocuslongus** [mjhoptics/opticalglass#5]
Hello Mike,

As you explain in the [documentation](https://ray-optics.readthedocs.io/en/latest/examples/ThorlabsLensImport/ThorlabsLensImport.html) and in reference to your [comment](https://github.com/mjhoptics/ray-optics/issues/46#issuecomment-846204701) on [this issue](https://github.com/mjhoptics/ray-optics/issues/46), a glass not found in ray-optics catalog can be manually input using the .smx file associated to the loaded zemax model.

It took me some time to find out that the glass name is case sensitive.

Following your [explanations](https://github.com/mjhoptics/ray-optics/issues/46#issuecomment-846204701), after modifying the smx file and reloading the model with `opm_asph, info_asph = open_model...`, I've gotten an error partially reproduced here:

```
KeyError                                  Traceback (most recent call last)
~/.virtualenvs/optics/lib/python3.8/site-packages/opticalglass/glassfactory.py in _create_glass(name, catalog)
     64                 # manufacturer's names.
---> 65                 gn, gc = _catalog_list[catalog].glass_lookup[gn_decode]
     66             except KeyError:

KeyError: (('ZLAF', '52'), 'D', 'LA')

During handling of the above exception, another exception occurred:

GlassNotFoundError                        Traceback (most recent call last)
[...]
     65                 gn, gc = _catalog_list[catalog].glass_lookup[gn_decode]
     66             except KeyError:
---> 67                 raise ge.GlassNotFoundError(catalog, name)
     68             else:
     69                 return _catalog_list[catalog].create_glass(gn, gc)

GlassNotFoundError: ('CDGM', 'D-ZLAF52LA')
```
After browsing and digging in the opticalglass code, I found that the D-ZLAF52LA is actually named D-ZLaF52LA (found in the CDGM.xls and `glass_list` and `glass_lookup` [here](https://opticalglass.readthedocs.io/en/latest/opticalglass.html#opticalglass.cdgm.CDGMCatalog))

The origin of the error can be reproduced from a python session (without having to resort to a python notebook):

```
>>> import opticalglass
>>> from opticalglass import glassfactory
>>> create_glass('D-ZLAF52LA','CDGM')
```
will return the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'create_glass' is not defined
>>> glassfactory.create_glass('D-ZLAF52LA','CDGM')
Traceback (most recent call last):
  File "/home/ludo/.virtualenvs/optics/lib/python3.8/site-packages/opticalglass/glassfactory.py", line 65, in _create_glass
    gn, gc = _catalog_list[catalog].glass_lookup[gn_decode]
KeyError: (('ZLAF', '52'), 'D', 'LA')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.virtualenvs/optics/lib/python3.8/site-packages/opticalglass/glassfactory.py", line 82, in create_glass
    return _create_glass(name, catalog)
  File "~/.virtualenvs/optics/lib/python3.8/site-packages/opticalglass/glassfactory.py", line 67, in _create_glass
    raise ge.GlassNotFoundError(catalog, name)
opticalglass.glasserror.GlassNotFoundError: ('CDGM', 'D-ZLAF52LA')
```
While this finds the glass:
```
>>> glassfactory.create_glass('D-ZLaF52LA','CDGM')
CDGMGlass('D-ZLaF52LA')
```
Do you think it could be useful for the glass name (more precisely, per reference to the function `decode_glass_name`, the glass `group`) to be read regardless of the case lower or upper, or does the case matters and no related misspell is allowed here?

I had started to see how to make a dictionary case insensitive, something along the following lines could work:
```
class CaseInsensitiveDict(dict):
    @classmethod
    def _k(cls, key):
        return key.lower() if isinstance(key, str) else key

    def __init__(self, *args, **kwargs):
        super(CaseInsensitiveDict, self).__init__(*args, **kwargs)
        self._convert_keys()
    def __getitem__(self, key):
        return super(CaseInsensitiveDict, self).__getitem__(self.__class__._k(key))
    def __setitem__(self, key, value):
        super(CaseInsensitiveDict, self).__setitem__(self.__class__._k(key), value)
    def __delitem__(self, key):
        return super(CaseInsensitiveDict, self).__delitem__(self.__class__._k(key))
    def __contains__(self, key):
        return super(CaseInsensitiveDict, self).__contains__(self.__class__._k(key))
    def has_key(self, key):
        return super(CaseInsensitiveDict, self).has_key(self.__class__._k(key))
    def pop(self, key, *args, **kwargs):
        return super(CaseInsensitiveDict, self).pop(self.__class__._k(key), *args, **kwargs)
    def get(self, key, *args, **kwargs):
        return super(CaseInsensitiveDict, self).get(self.__class__._k(key), *args, **kwargs)
    def setdefault(self, key, *args, **kwargs):
        return super(CaseInsensitiveDict, self).setdefault(self.__class__._k(key), *args, **kwargs)
    def update(self, E={}, **F):
        super(CaseInsensitiveDict, self).update(self.__class__(E))
        super(CaseInsensitiveDict, self).update(self.__class__(**F))
    def _convert_keys(self):
        for k in list(self.keys()):
            v = super(CaseInsensitiveDict, self).pop(k)
            self.__setitem__(k, v)
```
 [source](https://stackoverflow.com/a/32888599/6358973)

Alternatively, all names in all the glass spreadsheets could be converted to upper cases and when a glass name is to be decoded, the input glass name string be converted to upper case.

Ludo

**Comment by mjhoptics** [comment]
Ludo,
There are a couple of things going on here and I'm heading out of town for the week, so updates will be delayed.

- A one line change in decode_glass_name so the decoded pieces are always upper case fixes the command line case above.
- the original zemax import file specifies 2 glass catalogs; one that isn't supported in `ray-optics`. It only searches the remaining catalog, Schott, which doesn't even have a close match. Adding CDGM to the GCAT line in the .zmx file will get a match with the existing code.
- the `dict` definition in the .smx file has nested sets of quotes, which have to be paired up together correctly or the json importer gets upset. I suspect that's what happened.
- concerning the actual lens itself, it appears to be very well corrected when the lens and window/cover glass are used together. Run the analyses in your notebook on the model before you remove the plate. Notice how well corrected it is compared to when the plate is removed.

Mike

**Comment by diplodocuslongus** [comment]
Mike, 
Noted your proposed changes and explanations.
For the lens, I've run simulations with and without the cover glass and had updated my [original post](https://github.com/mjhoptics/ray-optics/issues/46#issuecomment-846762740) with layout diagrams and some text.

No problem at all for any delay, be safe!

Ludo

**Comment by mjhoptics** [comment]
Release v0.7.6 of opticalglass and v0.7.1 of rayoptics fix this issue.
